### ISSUE TITLE
Record "off-chain" orders from our interface

### ISSUE THREAD

**Issue by JonathonDunford** [forkdelta/backend-replacement#13]
We need to record orders from our interface in a queue.

Worker should push orders to ED's server using their WS API.
If ED's server is down, the worker should try again when the server is back up.

Order will be stored in our database and users can still trade that order regardless of if it is on ED or not.

**Comment by EeevilPopTart** [comment]
So I can do this, but it's not going to scale well.  Here's why:  1.) EtherDelta's down and has been for a while.  But let's assume they fix it and it comes back up.  2.) They rate limit.  You're only allowed to make ~7-8 orderbook/message calls per minute.  I'm not sure how many orderbook calls you're making per minute (if any), but let's just assume you're making 1.  That leaves 6-7 calls per minute to ED's backend for "message" calls.  Message calls are the ones used for posting new orders.  If ForkDelta catches on and gets a lot of new users, you should expect more than 6 new orders being posted per minute.  That doesn't even include retries.  ED's backend is super shitty.  About 50% of the calls will fail.  I'm not sure if those get counted towards the rate limit or not.  So you could be limited to around ~3/4 message posts per minute.  

I suggest building in a queue system, and when an order needs forwarded to ED's orderbook, you simply insert it into the queue with an expiration date (being like 5 minutes).  That way worst case it retries for only a few minutes before it expires and just gets removed from the queue.  In that case, it would live on the ForkDelta orderbook and not ED's orderbook.  If it succeeded, then it would live on both orderbooks (which is desired).  If it fails, it'll either be because ED's backend sucks or because you've been hitting the rate limit for too long and the retries were dropped.

**Comment by freeatnet** [comment]
Closing this. We have added order recording, but the likelihood of us ever needing a cross-poster is shrinking with every day.

**Comment by JonathonDunford** [comment]
@freeatnet Thoughts?
